version: '3.7'
services:
  cypress:
    image: "cypress/included:3.4.1"
    entrypoint: npm run cy:run
    environment:
      - CYPRESS_baseUrl=https://linkedin.com
    working_dir: /e2e
    volumes:
      - ./:/e2e
